# Generated by Django 5.0 on 2024-01-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="leader",
        ),
        migrations.AlterField(
            model_name="log",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="core.category",
            ),
        ),
    ]
