# Generated by Django 5.0 on 2024-01-04 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_team_leader_alter_log_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="log",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.log",
            ),
        ),
    ]
