# Generated by Django 5.0 on 2024-01-04 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_category_team_comment_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="liked_user",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
