# Generated by Django 5.0 on 2024-01-08 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_log_liked_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="activity_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exercise", "운동"),
                    ("reading", "독서"),
                    ("work", "업무"),
                    ("study", "공부"),
                    ("employment", "취업"),
                    ("job_change", "이직"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="personality_type",
            field=models.CharField(
                blank=True,
                choices=[("introverted", "내향형"), ("extroverted", "외향형")],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="preference_type",
            field=models.CharField(
                blank=True,
                choices=[("morning", "아침형"), ("evening", "저녁형")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="status_type",
            field=models.CharField(
                blank=True,
                choices=[("online", "온라인"), ("offline", "오프라인")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="liked_user",
            field=models.ManyToManyField(
                blank=True, related_name="liked_logs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
