# Generated by Django 5.0 on 2024-01-10 10:09

import config.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_team_activity_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exercise", "운동"),
                            ("reading", "독서"),
                            ("study", "공부"),
                            ("work", "업무"),
                            ("friendship", "친목"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=config.utils.upload_path
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="team",
            name="image",
        ),
        migrations.AddField(
            model_name="team",
            name="concept_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="core.conceptimage",
            ),
        ),
    ]
