# Generated by Django 5.0 on 2024-01-03 06:40

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_team_leader_alter_log_category"),
        ("user", "0002_authtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성시간"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정됨")),
                (
                    "id",
                    models.CharField(
                        default=user.models.generate_hex,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_leader", models.BooleanField(default=False)),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member",
                        to="core.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
